#!/bin/sh
exec 2>&1
# Set custom system settings to prevent potential attacks againts the machine

# Disable acceptance of source-routed packets to prevent spoofing attacks
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route

# Enable TCP SYN cookie protection to prevent SYN flood attacks
echo 1 > /proc/sys/net/ipv4/tcp_syncookies

# Disable acceptance of ICMP redirect messages to prevent malicious route changes
echo 0 > /proc/sys/net/ipv4/conf/all/accept_redirects

# Disable sending of ICMP redirect messages to prevent misleading other hosts
echo 0 > /proc/sys/net/ipv4/conf/all/send_redirects

# Enable source address spoofing protection
echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter

# Log packets with invalid source addresses to help detect potential issues
echo 1 > /proc/sys/net/ipv4/conf/all/log_martians

# Enable IP forwarding for NAT
echo 1 > /proc/sys/net/ipv4/ip_forward

# Disable acceptance of ICMP router advertisements (IPv6)
echo 0 > /proc/sys/net/ipv6/conf/all/accept_ra
echo 0 > /proc/sys/net/ipv6/conf/default/accept_ra

# Disable acceptance of IPv6 redirects
echo 0 > /proc/sys/net/ipv6/conf/all/accept_redirects
echo 0 > /proc/sys/net/ipv6/conf/default/accept_redirects

# Disable IPv6 (if you are not using it)
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
echo 1 > /proc/sys/net/ipv6/conf/default/disable_ipv6

# Restrict the maximum number of half-open connections to mitigate SYN flood attacks
echo 2048 > /proc/sys/net/ipv4/tcp_max_syn_backlog

# Enable Reverse Path Filtering to prevent IP spoofing
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do
    echo 1 > $f
done

[ ! -e /etc/iptables/iptables.rules ] && exit 0
iptables-restore -w 3 /etc/iptables/iptables.rules || exit 1
exec chpst -b iptables pause
